### ISSUE TITLE
Custom Dyes

### ISSUE THREAD

**Issue by reteo** [jeffpengMC/SI-Mods#10]
Dual-use dyes:
* White dye = Bonemeal = fertilizer. 
* Brown dye = cocoa beans = food.

Hard-to-access dyes:
* Blue dye = Lapis Lazuli = must be mined
* Green dye = Cactus Green = Look for deserts or Horsetail

There are some dual-use dyes in the game that should be replaced (or at least supplemented) with dyes that only have one use: to change something's color.  And then there are dyes that are just hard to get to without playing for a long while.  I don't know if this is something that can currently be done with the si.core configuration, but it would mean the inclusion of Pam's "Weeee flowers" as a way to farm dyes without accidentally farming something more useful.

**Comment by jeffpengMC** [comment]
Feature is possible and scheduled for 1.4.2.

**Comment by jeffpengMC** [comment]
Done as of 1.4.1.2
