### ISSUE TITLE
si.core crash on servers.

### ISSUE THREAD

**Issue by reteo** [jeffpengMC/SI-Mods#11]
An error occurs when attempting to launche a server with si.core:

```
Caught exception from si.core
    java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.func_78013_b()Ljava/lang/String;
```

Logs are available in reteo/Survival-Industry#66

**Comment by jeffpengMC** [comment]
Solves as of 1.4.1.1

**Comment by t3mainframe** [comment]
As of 1.4.1.1 not fixed 2/5/2016
[23:24:05] [Server thread/ERROR] [FML]: Caught exception from si.core

**Comment by reteo** [comment]
The fix has been applied to the upcoming version of Survival Industry; A lot of changes have been applied to si.core mod, making it incompatible with the current release.  Please bear with us; the next version should be available in a couple weeks, once we've solved some additional issues.
